/**
 * Created by Administrator on 2017/3/9.
 */
var dataImg = {
    "data": [
        {"src": "img/con0.jpg"},
        {"src": "img/con1.jpg"},
        {"src": "img/con2.jpg"},
        {"src": "img/con3.jpg"},
        {"src": "img/con4.jpg"},
        {"src": "img/con5.jpg"},
        {"src": "img/con6.jpg"},
        {"src": "img/con7.jpg"},
        {"src": "img/con8.jpg"},
        {"src": "img/con9.jpg"},
        {"src": "img/con10.jpg"},
        {"src": "img/con11.jpg"},
        {"src": "img/con0.jpg"},
        {"src": "img/con1.jpg"},
        {"src": "img/con2.jpg"},
        {"src": "img/con3.jpg"},
        {"src": "img/con4.jpg"},
        {"src": "img/con5.jpg"},
        {"src": "img/con6.jpg"},
        {"src": "img/con7.jpg"},
        {"src": "img/con8.jpg"},
        {"src": "img/con9.jpg"},
        {"src": "img/con10.jpg"},
        {"src": "img/con11.jpg"},
        {"src": "img/con0.jpg"},
        {"src": "img/con1.jpg"},
        {"src": "img/con2.jpg"},
        {"src": "img/con3.jpg"},
        {"src": "img/con4.jpg"},
        {"src": "img/con5.jpg"},
        {"src": "img/con6.jpg"},
        {"src": "img/con7.jpg"},
        {"src": "img/con8.jpg"},
        {"src": "img/con9.jpg"},
        {"src": "img/con10.jpg"},
        {"src": "img/con11.jpg"},
        {"src": "img/con0.jpg"},
        {"src": "img/con1.jpg"},
        {"src": "img/con2.jpg"},
        {"src": "img/con3.jpg"},
        {"src": "img/con4.jpg"},
        {"src": "img/con5.jpg"},
        {"src": "img/con6.jpg"},
        {"src": "img/con7.jpg"},
        {"src": "img/con8.jpg"},
        {"src": "img/con9.jpg"},
        {"src": "img/con10.jpg"},
        {"src": "img/con11.jpg"},
        {"src": "img/con0.jpg"},
        {"src": "img/con1.jpg"},
        {"src": "img/con2.jpg"},
        {"src": "img/con3.jpg"},
        {"src": "img/con4.jpg"},
        {"src": "img/con5.jpg"},
        {"src": "img/con6.jpg"},
        {"src": "img/con7.jpg"},
        {"src": "img/con8.jpg"},
        {"src": "img/con9.jpg"},
        {"src": "img/con10.jpg"},
        {"src": "img/con11.jpg"}
    ]
};